language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
  - "pypy3"

env:
- TESTSUITE=unit
- TESTSUITE=functional
- TESTSUITE=smoke

install:
- pip install -r requirements/development.txt
- pip install coveralls

script:
- "coverage run manage.py test -v 1 tests.$TESTSUITE"
- coverage report

after_success:
  - "[[ $TESTSUITE != 'smoke' ]] && coveralls"
